### ISSUE TITLE
NoSuchElementException cell_1_6

### ISSUE THREAD

**Issue by nixpulvis** [Timidger/Fundies-Assignment-Downloader#2]
Running the example `python2 DownloadAssignments.py  names.txt 4` yields the following error.

```
Traceback (most recent call last):
  File "DownloadAssignments.py", line 230, in <module>
    main()
  File "DownloadAssignments.py", line 207, in main
    navigate_to_jump_to(driver)
  File "DownloadAssignments.py", line 100, in navigate_to_jump_to
    cell = driver.find_element_by_id("cell_1_6")
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 234, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 712, in find_element
    {'using': by, 'value': value})['value']
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 201, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 181, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"cell_1_6"}
  (Session info: chrome=46.0.2490.71)
  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Mac OS X 10.11.0 x86_64)
```

**Comment by Timidger** [comment]
Alright, I just pushed some changes. I think it might be an OS X issue (and I unfortunately don't have a copy on hand to try it out), so I forced the user-agent to be the same as what my version of chrome is reporting for me. If that still does not fix the issue, I will attempt to borrow someone else's so I can look into making a proper work-around for OSX

**Comment by Timidger** [comment]
Ok, after trying it out on a friend's computer, I think I have fixed it. I made the size of the window automatically get big enough (because that was part of the issue), and I also made sure to only search for the cell id within the table `div` tag. Let me know if it still doesn't work, and I will do more rigorous testing.
